### ISSUE TITLE
点击左侧最后一个索引，会定位到最后第二个索引上

### ISSUE THREAD

**Issue by 179098051** [wustor/GangedRecyclerview#1]
还有就是滑动右侧的，左侧的要是不可见，将其滑动至可见应该会比较好吧， 类似拼多多 搜索界面的效果

**Comment by xgeeek** [comment]
数据条目太多的时候，滚动的时间感觉有点长。能像qq或者微信那样，一下滚动到位置就好了。

**Comment by wustor** [comment]
谢谢提醒，我正在优化

**Comment by yihuangxing** [comment]
你好，我想请教你下，mSortDetailFragment.setData(position * 10 + position);这是甚么意思啊？为啥是乘10，是不是因为for (int j = 0; j < 10; j++) {
                SortBean sortBean = new SortBean(String.valueOf(i + "行" + j + "个"));
                sortBean.setTag(String.valueOf(i));
                mDatas.add(sortBean);
            }这个集合的大小为10，所以才乘的10？

**Comment by wustor** [comment]
已经提交了最新的版本，针对你们提的issue已经进行了优化，现在左侧选中的item能够居中，你们提issue的时候如果是不同的问题，希望能够单独提issue，不要在别人的issue下面提，这样我不好回复。

**Comment by wustor** [comment]
yihuangxing你的理解是对的，原理就是要计算左侧点击的这个分类的position切换成为右边的Recyclerview里面的position，然后进行滚动，具体的计算方式就是把这个分类之前的所有集合中的item数量相加，比如说我现在点击了5，就需要把1,2,3,4这些分类的集合全部加在一起
