### ISSUE TITLE
有时候出现报空的情况

### ISSUE THREAD

**Issue by lxhtiamo** [wustor/GangedRecyclerview#10]
if (isTranslate) {
            canvas.restore();
        }
        Log.d("tag--->", tag + "VS" + currentTag);
        if (!TextUtils.equals(tag, currentTag)) {
            currentTag = tag;
            Integer integer = Integer.valueOf(tag);
            mCheckListener.check(integer, false);
        }

最下面一行 有时候出现报空的情况,这个我也无法复现,不知道什么时候会报,有时候是界面被覆盖时候太久时间时候出现的,

**Comment by wustor** [comment]
能贴一下日志不

**Comment by wustor** [comment]
对mCheckListener增加了判空，先关闭了
