### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by th-felix** [wustor/GangedRecyclerview#12]
点击左侧栏目，然后滑动右侧，发现只有滑动两个栏目左侧才会跳转，eg:点击保健品，滑动右侧，左侧只会跳转西药或者消毒品，不会跳转普通食品或医疗器械。

**Comment by xue12311** [comment]
这个可以将isMoved设置为静态变量，
 public static boolean isMoved = false;
 监听右边的RecyclerView的触摸事件
 mRecyclerView.addOnItemTouchListener(new RecyclerView.OnItemTouchListener() {
            @Override
            public boolean onInterceptTouchEvent(RecyclerView rv, MotionEvent e) {
                if (MotionEvent.ACTION_DOWN == e.getAction()) {
                    if (XXXFrament.isMoved) {
                        XXXFrament.isMoved = false;
                    }
                }
                return false;
            }
            @Override
            public void onTouchEvent(RecyclerView rv, MotionEvent e) { }
            @Override
            public void onRequestDisallowInterceptTouchEvent(boolean disallowIntercept) { }
        });

**Comment by wustor** [comment]
这个问题跟[issue9](https://github.com/wustor/GangedRecyclerview/issues/9)是同一个问题，已经修复了
