### ISSUE TITLE
当 item_title 的高度大于 item_classify_detail 的高度时, 头布局偏移会有跳动

### ISSUE THREAD

**Issue by jhwsx** [wustor/GangedRecyclerview#13]
如题目所描述的那样. 我试着把 Demo 里边的 item_title 的高度改成大于 item_classify_detail 的高度, 测试发现可以出现同样的问题.
我自己也在想怎么解决这个问题, 虽然还没有解决办法. 可以帮我看一下吗?

**Comment by wustor** [comment]
会有这种使用场景么，title理论上不会比content高才对
