### ISSUE TITLE
老哥，你这个点击左侧列表倒数几个会一直显示右侧最后数据屏幕顶端位置对应的左侧那一个列表，像是bug一样，还有这个能提取出一个库吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [wustor/GangedRecyclerview#14]

**Comment by SaltedFish-Extreme** [comment]
还有我觉得点击左侧列表，右边的数据平滑滚动好一些

**Comment by wustor** [comment]
如果左侧某个item对应的右侧数据没有一屏，点击左侧多个item就会出现你说的那种情况，现在已经抽取成一个单独的module了，可以自己修改数据格式。

**Comment by SaltedFish-Extreme** [comment]
@wustor 好的老哥，我目前暂时先用已经不再维护的垂直TabLayout，以后如果出现类似的需求考虑用老哥你的这个试试，话说老哥可以把library发布到jitpack上，只需要打一个tag，这样只需要导入你github仓库地址的依赖就能直接调用了😊还有如果能有一份简要的说明文档就好了😆
![微信图片_20220202194748](https://user-images.githubusercontent.com/54784104/152148301-aee3d792-26a8-4339-8a6f-4dc0f76e9361.jpg)

**Comment by wustor** [comment]
好的，我改了之后，发布一下
