### ISSUE TITLE
大佬 我又来提bug了 

### ISSUE THREAD

**Issue by 179098051** [wustor/GangedRecyclerview#4]
谢谢大佬对每个意见都回复
 那个 我又发现一个bug，比如左侧我选了1 ，然后滑动至1不可见，滑动右边的会崩

**Comment by 179098051** [comment]
private boolean move;

    //将当前选中的item居中
    private void moveToCenter(final int position) {
        RecyclerView.LayoutManager layoutManager = rvSort.getLayoutManager();
        if (layoutManager instanceof LinearLayoutManager) {
            final LinearLayoutManager linearLayoutManager = ((LinearLayoutManager) layoutManager);
            //将点击的position转换为当前屏幕上可见的item的位置以便于计算距离顶部的高度，从而进行移动居中
            int fir = linearLayoutManager.findFirstVisibleItemPosition();
            int end = linearLayoutManager.findLastVisibleItemPosition();
            if (position <= fir) {
                rvSort.scrollToPosition(position);
            } else if (position <= end) {
                View childAt = rvSort.getChildAt(position - linearLayoutManager.findFirstVisibleItemPosition());
                int y = (childAt.getTop() - rvSort.getHeight() / 2);
                rvSort.smoothScrollBy(0, y);
            } else {
                rvSort.scrollToPosition(position);
                move = true;
            }

            rvSort.addOnScrollListener(new RecyclerView.OnScrollListener() {
                @Override
                public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                    super.onScrolled(recyclerView, dx, dy);
                    if (move) {
                        move = false;
                        int n = position - linearLayoutManager.findFirstVisibleItemPosition();
                        if (n >= 0 && n < rvSort.getChildCount()) {
                            rvSort.scrollBy(0, rvSort.getChildAt(n).getTop());
                        }
                    }
                }
            });
        }

    }

我这样修改了 貌似不崩了

**Comment by 179098051** [comment]
改过之后 发现滑动右边的 左侧有的时候滑动不会变了，蛋疼  还是大佬您改吧

**Comment by cqq1234** [comment]
点击了左侧 数据14 以后，再滑动右边列表，左侧不会联动了。

**Comment by wustor** [comment]
新版本已经修复
