### ISSUE TITLE
有快速引用的方法吗

### ISSUE THREAD

**Issue by ydBen** [wustor/GangedRecyclerview#5]
代码封装的太好了不会在fragment中使用，可能是context传递的一些问题。那些类是必要的，为什么会用到fragment。好像是因为getAssetsData没有获取到数据，String assetsData = getAssetsData("sort.json")这个数据是怎么得到的。找到了，要在assets中放入模拟数据，谢谢大神，代码很好用。

**Comment by wustor** [comment]
是一样的，我项目中就是在Fragment中使用的，只是需要在Fragment中嵌套Fragment而已，你说的这个封装我也在考虑，因为是多个控件在一起交互，所以不太好封装，不过我最近在尝试，谢谢关注
