### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by Davy103** [wustor/GangedRecyclerview#7]
当右边的数据很多的时候，点击左边的菜单栏会有卡顿，有时超过了三秒才滑动到相应的位置，这个可以优化下么？
还有如果右边的数据展示改成一行只显示一个数据的时候，往上滑动的时候，当滑到这个列表倒数第二个的时候，头部的标题栏就被顶上去了，然后又回来的？直到这个分类滑完后标题栏才消失的，、。
麻烦解答下，谢谢

**Comment by wustor** [comment]
谢谢提醒哈，最近比较忙，你能给我一个demo吗，fat_chao@163.com,我来看一下

**Comment by Davy103** [comment]
好的，已发邮箱给你了，谢谢哈。
