### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by SkyHots** [wustor/GangedRecyclerview#9]
楼主在吗，demo中发现一个小bug 点击选中左侧的某一项，然后缓慢滑动右侧的列表，当右侧列表滑动到下一项时，左侧的下一项并不会被选中，继续滑动到下一项，左侧选中状态才恢复正常。

**Comment by wustor** [comment]
最近在忙着换工作的事情，这个问题我记下来了，我抽空看一下，谢谢提醒

**Comment by Liby94** [comment]
```
else
{
 if (isMoved) {
        isMoved = false;
  } else
        mSortAdapter.setCheckedPosition(position);
        ItemHeaderDecoration.setCurrentTag(String.valueOf(position));//如果是滑动右边联动左边，则按照右边传过来的位置作为tag
}
```
在MainActivity类中这个isMoved个人猜测是为防止左侧点击后右侧的列表滑动做的一个处理。但是这个会消费掉下一个滑动的对应关系。
改成下面应该也没问题吧？
```
else
{
        mSortAdapter.setCheckedPosition(position);
        ItemHeaderDecoration.setCurrentTag(String.valueOf(position));//如果是滑动右边联动左边，则按照右边传过来的位置作为tag
}
```

**Comment by blankfu** [comment]
@Liby94 改了之后是没那种问题了。谢谢~

**Comment by shiner0** [comment]
楼主在吗，demo中发现一个小bug 点击选中左侧的某一项，然后缓慢滑动右侧的列表，当右侧列表滑动到下一项时，左侧的下一项并不会被选中，继续滑动到下一项，左侧选中状态才恢复正常      @wustor 这个问题没有修复

**Comment by wustor** [comment]
问题定位到了，这种情况只有当左侧先被点击后，再缓慢滑动右侧才会出现，今天尝试复现了，已经修复了，抱歉这么久才回复。详见commit点05fe2b4f9583e30fb0c7934d158dd91630802327
